package kotlintest.vishu.com.kotlintest.utilities

class  MyConstants {
    companion object {
        val MY_PREFERENCES = "preferences"
        val TOKEN = "token"
        val OTP = "otp"
        val LAT = "lat"
        val LNG = "lng"
        val MOBILE = "mobile"
        val ADDRESS_ID = "addressId"
        val START_DELIVERY_DATE = "date"
        val SUBSCRIPTION_ID = "subscription_id"
        val STATUS = "status"
        val CITY_ID = "cityid"
        val ZONE_ID = "zoneid"
        val REG_ID = "regid"
        val LOGIN_DONE = "login_done"
        var LOGIN_DONE_DATA = ""
        var REG_ID_DATA = ""
        val SENT_REG_ID = "sent reg id"
        var SENT_REG_ID_DATA = ""
        var MOBILE_DATA = "User Mobile"
        var OTP_DATA = "Otp Data"
        var TOKEN_DATA = "Otp Data"
        var LAT_DATA = ""
        var LNG_DATA = ""
        var ADDRESS_ID_DATA = ""
        var START_DELIVERY_DATE_DATA = ""
        var SUBSCRIPTION_ID_DATA = ""
        var STATUS_DATA = ""
        var CITY_ID_DATA = ""
        var ZONE_ID_DATA = ""
    }
}
